coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: true
    patch:
      default:
        target: 70%
        informational: true

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false

ignore:
  - "build.rs"
  - "**/tests/**"
  - "**/examples/**"
  - "docker/**"
  - "scripts/**"
