version: "3.8"
services:
  server:
    image: ghcr.io/matter-labs/zksync-os-server:v0.13.0
    container_name: server
    platform: linux/amd64
    restart: unless-stopped
    user: "0:0"
    working_dir: /app
    ports:
      - "3050:3050"
    environment:
      sequencer_base_fee_override: "0x3e8"
      sequencer_pubdata_price_override: "0x1"
      sequencer_native_price_override: "0x1"
      sequencer_block_dump_path: "/chain/db/block_dumps"

      general_rocks_db_path: "/chain/db/node1"
      general_l1_rpc_url: "https://rpc.ab.testnet.adifoundation.ai"

      # To get server params such as:
      #  - `genesis_bridgehub_address`
      #  - `genesis_bytecode_supplier_address`
      #  - `l1_sender_operator_commit_pk`
      #  - `l1_sender_operator_prove_pk`
      #  - `l1_sender_operator_execute_pk`
      #
      # run command: `adi server-params`

      genesis_bytecode_supplier_address: "0x9FCBe7dD5aa25c63A7cC3810EE38873d9eC6ED7c"
      genesis_genesis_input_path: "/genesis/genesis.json"
      l1_sender_max_fee_per_blob_gas_gwei: 15

      genesis_bridgehub_address: "0x076e1622cb6181b05aEC9B4aB7B1fFe6020834f5"
      genesis_chain_id: 222

      prover_api_object_store_file_backed_base_path: "/shared"
      prover_api_component_enabled: "false"
      prover_api_fake_fri_provers_enabled: "true"
      prover_api_fake_snark_provers_enabled: "true"
      prover_api_address: "0.0.0.0:3320"
      prover_input_generator_app_bin_unpack_path: "/chain/db/app_bins"
      prover_input_generator_maximum_in_flight_blocks: 120

      batcher_batch_timeout: "10s"
      batcher_blocks_per_batch_limit: 10

      l1_sender_operator_commit_pk: "0xa1f4a74ca5af0fd874a8cb68bb7c3c1c38be37072f8ef744bdfad7bec38df2f8"
      l1_sender_operator_prove_pk: "0x8af75ce9d789be73bab5e31959d8dc6f3100aa5ae15c886e79a11305aecdb170"
      l1_sender_operator_execute_pk: "0x56a97ee9fb652352c21a4b48b6aa5624a6d6cd269a91b0f4c9d48b739dbc6c27"
      l1_sender_max_fee_per_gas_gwei: 1500
      l1_sender_max_priority_fee_per_gas_gwei: 1500

      l1_sender_fusaka_upgrade_timestamp: 1771883505
      l1_sender_pubdata_mode: "Calldata"

      RUST_LOG: "info,zksync_os_server=debug,zksync_os_sequencer=info,zksync_os_merkle_tree=info,zksync_os_priority_tree=info"
    volumes:
      - ./state/volumes/chain:/chain
      - ./state/volumes/shared:/shared
      # Change path to the genesis.json
      - ./state/l3eco/chains/adi/configs/genesis.json:/genesis/genesis.json:ro
