# https://taskfile.dev

version: "3"

tasks:
  _install_rust:
    internal: true
    status:
      - rustc --version
    cmds:
      - curl https://sh.rustup.rs -sSf | sh

  build:
    deps:
      - _install_rust
    cmds:
      - cargo build

  build:docker:
    desc: Build Docker images using Docker Bake
    vars:
      TARGETS: '{{default "default" .TARGETS}}'
    sources:
      - docker/worker/Dockerfile
      - docker/docker-bake.hcl
    generates:
      - .task/build_docker_{{.TARGETS}}
    preconditions:
      # Check if docker is running and have required commands
      - docker ps
      - docker buildx version
      - docker buildx bake --help
    cmds:
      - docker buildx bake -f docker/docker-bake.hcl {{.TARGETS}}
      - mkdir -p .task && touch .task/build_docker_{{.TARGETS}}
